# Generated by Django 5.1.1 on 2024-09-16 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100, verbose_name='Texto do e-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Ocupacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupacao', models.CharField(max_length=100, verbose_name='Ocupação')),
            ],
        ),
        migrations.CreateModel(
            name='Perguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=100, verbose_name='Enunciado do questionário')),
                ('alternativa_a', models.CharField(max_length=100, verbose_name='Alternativa A')),
                ('alternativa_b', models.CharField(max_length=100, verbose_name='Alternativa B')),
                ('alternativa_c', models.CharField(max_length=100, verbose_name='Alternativa C')),
                ('alternativa_d', models.CharField(max_length=100, verbose_name='Alternativa D')),
                ('alternativa_correta', models.CharField(max_length=100, verbose_name='Alternativa correta')),
            ],
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do questionário')),
                ('data_criacao', models.DateField(verbose_name='Data de criação do questionário')),
                ('nivel', models.CharField(max_length=100, verbose_name='Nível do questionário')),
                ('perguntas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.perguntas')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do usuário')),
                ('conteudo', models.CharField(max_length=100, verbose_name='Nome do usuário')),
                ('administrador', models.CharField(max_length=100, verbose_name='Nome do usuário')),
                ('questionario_do_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.questionario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do usuário')),
                ('cpf', models.IntegerField(verbose_name='CPF do usuário')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail do usuário')),
                ('senha', models.CharField(max_length=100, verbose_name='Senha do usuário')),
                ('ocupacao_do_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ocupacao')),
            ],
        ),
        migrations.CreateModel(
            name='Material_Adicionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.material')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usuario')),
            ],
        ),
    ]
