# Generated by Django 5.1.1 on 2024-09-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_material_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Material_Adicionado',
            new_name='MaterialAdicionado',
        ),
        migrations.AlterModelOptions(
            name='perguntas',
            options={'verbose_name': 'Pergunta', 'verbose_name_plural': 'Perguntas'},
        ),
        migrations.AlterField(
            model_name='material',
            name='conteudo',
            field=models.TextField(verbose_name='Conteúdo do material'),
        ),
        migrations.AlterField(
            model_name='perguntas',
            name='enunciado',
            field=models.CharField(max_length=100, verbose_name='Enunciado da pergunta'),
        ),
        migrations.RemoveField(
            model_name='questionario',
            name='perguntas',
        ),
        migrations.AddField(
            model_name='questionario',
            name='perguntas',
            field=models.ManyToManyField(to='app.perguntas', verbose_name='Perguntas do questionário'),
        ),
    ]
